Repository yuheho7749/uwufs, pull requests merged in 2024-11, with the labels that each got.

#5 Basic skeleton for entire project (+ functional root directory)
  Makefile
  README.md
  src/test/test.c
  src/uwufs/README.md
  src/uwufs/file_operations.c
  src/uwufs/file_operations.h
  src/uwufs/low_level_operations.c
  src/uwufs/low_level_operations.h
  src/uwufs/mkfs_uwu.c
  src/uwufs/mount_uwufs.c
  src/uwufs/syscalls.c
  src/uwufs/syscalls.h
  src/uwufs/uwufs.h
Labels: documentation, enhancement, help wanted

#6 Change access flag name to file mode and removed size argument from write_blk
  src/test/test.c
  src/uwufs/file_operations.c
  src/uwufs/file_operations.h
  src/uwufs/low_level_operations.c
  src/uwufs/low_level_operations.h
  src/uwufs/mkfs_uwu.c
  src/uwufs/syscalls.c
  src/uwufs/uwufs.h
Labels: documentation, patch

#12 [HOTFIX] namei bug
  src/uwufs/file_operations.c
  src/uwufs/low_level_operations.c
  src/uwufs/syscalls.c
Labels: hotfix

#11 [PATCH] Increased file name size
  Makefile
  src/test/test.c
  src/uwufs/file_operations.c
  src/uwufs/uwufs.h
Labels: enhancement, patch

#13 create (regular file) syscall + bugfix
  Makefile
  src/test/test.c
  src/uwufs/file_operations.c
  src/uwufs/mount_uwufs.c
  src/uwufs/syscalls.c
  src/uwufs/syscalls.h
  src/uwufs/uwufs.h
Labels: enhancement, bugfix

#16 unlink and utimens syscall
  Makefile
  README.md
  src/uwufs/file_operations.c
  src/uwufs/file_operations.h
  src/uwufs/mkfs_uwu.c
  src/uwufs/mount_uwufs.c
  src/uwufs/syscalls.c
  src/uwufs/uwufs.h
Labels: documentation, enhancement

#32 Dev/indirect blocks
  .gitignore
  Makefile
  src/phase1/spam-mail.c
  src/test/c_api_test.cpp
  src/test/cpp_inode_tests.cpp
  src/test/test.c
  src/test/test.sh
  src/uwufs/cpp/DataBlockIterator.cpp
  src/uwufs/cpp/DataBlockIterator.h
  src/uwufs/cpp/INode.cpp
  src/uwufs/cpp/INode.h
  src/uwufs/cpp/c_api.cpp
  src/uwufs/cpp/c_api.h
  src/uwufs/file_operations.c
  src/uwufs/file_operations.h
  src/uwufs/low_level_operations.c
  src/uwufs/low_level_operations.h
  src/uwufs/mkfs_uwu.c
  src/uwufs/mount_uwufs.c
  src/uwufs/syscalls.c
  src/uwufs/uwufs.h
Labels: bug, documentation, enhancement, bugfix
